server:
  port:
    8087

spring:
  application:
    name: ead-authuser
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser?useSSL=false&serverTimezone=America/Sao_Paulo
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update